/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.items {
	import laya.ui.*;
	import laya.display.*;

	public class MenuBtnUI extends View {
		public var btn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Button","props":{"width":120,"var":"btn","skin":"commers/btn3.png","sizeGrid":"6,6,6,6","labelSize":20,"labelColors":"#FFFFFF,#FFFFFF,#FFFFFF","label":"公司审核","height":50},"compId":3}],"loadList":["commers/btn3.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}