/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import laya.display.Sprite;
	import LogPanelControl;

	public class LogPanelUI extends View {
		public var mainpanel:Panel;
		public var bgimg:Image;
		public var input_account:TextInput;
		public var input_pwd:TextInput;
		public var btn_login:Button;
		public var closebtn:Button;
		public var txt_forget:Text;
		public var txt_reg:Text;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("LogPanel");

		}

	}
}