/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.viewpage {
	import laya.ui.*;
	import laya.display.*;
	import script.groupAudit.GroupAuditControl;

	public class GroupAuditViewUI extends Scene {
		public var rtInfoInput:TextInput;
		public var statusRadio:RadioGroup;
		public var searchBtn:Button;
		public var requestlist:List;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("viewpage/GroupAuditView");

		}

	}
}