/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.viewpage {
	import laya.ui.*;
	import laya.display.*;
	import script.MainPageControl;

	public class MainPageUI extends Scene {
		public var account:Label;
		public var quitBtn:Button;
		public var menulist:List;
		public var container:Sprite;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("viewpage/MainPage");

		}

	}
}