/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.viewpage {
	import laya.ui.*;
	import laya.display.*;
	import util.PictureCheckControl;

	public class PicCheckPanelUI extends View {
		public var imgbg:Image;
		public var mainpanel:Panel;
		public var img:Image;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("viewpage/PicCheckPanel");

		}

	}
}